### ISSUE TITLE
Could you also upload the training file?

### ISSUE THREAD

**Issue by yougyoung94** [ManWingloeng/nailtracking#1]
Hello! I got a huge help from your git!
Could you also upload code so that I can see how you built and trained your model?
Thanks for your help:):)

**Comment by toddwyl** [comment]
> Hello! I got a huge help from your git!
> Could you also upload code so that I can see how you built and trained your model?
> Thanks for your help:):)

I train the model with the [official training object_detection repo](https://github.com/tensorflow/models/tree/master/research/object_detection) in tesorflow/model. I cannot upload the nail data now, but u can crawl them down online.@yougyoung94

**Comment by toddwyl** [comment]
> Hello! I got a huge help from your git!
> Could you also upload code so that I can see how you built and trained your model?
> Thanks for your help:):)

About 3127 pictures for training. I can offer u the pictures now, but I cannot offer the
annotation file (xml file) to u.
U can download on link below:
link: https://pan.baidu.com/s/1sl4BTTE-N_nYQYns_AfGjg
password: pac6

**Comment by fathimac** [comment]
Hi,

I am trying to implement something similar. I tried accessing the link: https://pan.baidu.com/s/1sl4BTTE-N_nYQYns_AfGjg But it's not working. If you don't mind could you please help with this.

Thanks,

**Comment by toddwyl** [comment]
> Hi,
> 
> I am trying to implement something similar. I tried accessing the link: https://pan.baidu.com/s/1sl4BTTE-N_nYQYns_AfGjg But it's not working. If you don't mind could you please help with this.
> 
> Thanks,

I check it again. It is ok. 
But u need to download the windows app which named 百度网盘. 
[Download url](https://pan.baidu.com/download)
I am sorry about that, but I have no enough space in dropbox. 
Can u try it again?

**Comment by sealedtx** [comment]
@ManWingloeng Hi, thank you for sharing your dataset, but could please upload it to google drive? It is difficult to download from baidu for people living outside China

**Comment by toddwyl** [comment]
> @ManWingloeng Hi, thank you for sharing your dataset, but could please upload it to google drive? It is difficult to download from baidu for people living outside China

@sealedtx @fathimac 
I share the dataset on google drive. 
Download url: [Google Drive](https://drive.google.com/file/d/1RCfKiL7IRYMFIKLjhffCywU-Mf-jySZz/view?usp=sharing)

**Comment by lvv93** [comment]
@ManWingloeng Hello, thank you for sharing and I'm very interested in it. Could you please upload the annotation file because I don't know how to annotate it? Thank you.

**Comment by toddwyl** [comment]
> @ManWingloeng Hello, thank you for sharing and I'm very interested in it. Could you please upload the annotation file because I don't know how to annotate it? Thank you.

Sorry, because the annotation files is not my property, u can use **labelme** or **labelimg** to annotate it.
