### ISSUE TITLE
Free-Form Nail Cropping

### ISSUE THREAD

**Issue by Skeli789** [ManWingloeng/nailtracking#10]
Is there some way of running the code so that it will generate some set of points outlining _only_ the nail in the image (as opposed to just a square around it)? I was hoping to extract nails out from the background around them. While cropping down to a square is extremely helpful (and I commend you on that), it doesn't go far enough for my project, unfortunately.

**Comment by toddwyl** [comment]
Sorry @Skeli789 . At present, it is only for **nail tracking**.
If it is about **semantic segmentation**, you can try other end-to-end deep learning models. 
Maybe you can use unsupervised segmentation after the nail detection, because I think data labeling is quite **troublesome**.

**Comment by Skeli789** [comment]
Thank you for your advice! I used your model as a base for the semantic segmentation, and it's working perfectly!

**Comment by lokkju** [comment]
> Thank you for your advice! I used your model as a base for the semantic segmentation, and it's working perfectly!

Do you have any plans to share your code/techniques? I'm quite interested as well!
