### ISSUE TITLE
Regarding training data

### ISSUE THREAD

**Issue by AlphaNumeric99** [ManWingloeng/nailtracking#2]
I understand that you cant post your image data set like you mentioned in another issue so i want to ask how many images approximately do i need for a decent accuracy like this?

**Comment by ManWingloeng** [comment]
About 3127 pictures for training. I can offer u the pictures now, but I cannot offer the 
annotation file (xml file) to u.
U can download on link below:
**link: https://pan.baidu.com/s/1sl4BTTE-N_nYQYns_AfGjg** 
**password: pac6**

**Comment by ManWingloeng** [comment]
> I understand that you cant post your image data set like you mentioned in another issue so i want to ask how many images approximately do i need for a decent accuracy like this?

About 3127 pictures for training. I can offer u the pictures now, but I cannot offer the
annotation file (xml file) to u.
U can download on link below:
link: https://pan.baidu.com/s/1sl4BTTE-N_nYQYns_AfGjg
password: pac6

**Comment by AlphaNumeric99** [comment]
Thank you.

**Comment by sealedtx** [comment]
@ManWingloeng Hi, thank you for sharing your dataset, but could please upload it to google drive?
