### ISSUE TITLE
Extremely slow FPS on my laptop cam

### ISSUE THREAD

**Issue by AlexYiningLiu** [ManWingloeng/nailtracking#3]
When I run infer.py, the output frames come at an extremely slow frame rate, much slower than the output GIF on the repo's README page. I am wondering if this is something wrong on my end or if the code is supposed to be this slow? Please let me know if it's possible to get a smoother output with higher FPS. Thanks.

**Comment by toddwyl** [comment]
> When I run infer.py, the output frames come at an extremely slow frame rate, much slower than the output GIF on the repo's README page. I am wondering if this is something wrong on my end or if the code is supposed to be this slow? Please let me know if it's possible to get a smoother output with higher FPS. Thanks.

There is some useful **tips** how I get higher FPS:
- Detect the nails on every few frames instead of every frame.
- Resize the frame to smaller.
- Convert model to tflite. (use `tf.lite.TFLiteConverter.from_frozen_graph` convert pb file to tflite FP16.)

**Comment by AlexYiningLiu** [comment]
> > When I run infer.py, the output frames come at an extremely slow frame rate, much slower than the output GIF on the repo's README page. I am wondering if this is something wrong on my end or if the code is supposed to be this slow? Please let me know if it's possible to get a smoother output with higher FPS. Thanks.
> 
> There is some useful **tips** how I get higher FPS:
> 
> * Detect the nails on every few frames instead of every frame.
> * Resize the frame to smaller.
> * Convert model to tflite. (use `tf.lite.TFLiteConverter.from_frozen_graph` convert pb file to tflite FP16.)

Thanks for your reply. I understand how to do the first steps but how do you convert model to tflite? Can you let me know what exact code you used to perform the 3rd step? Thanks.
