### ISSUE TITLE
Distinguish between different nails

### ISSUE THREAD

**Issue by AlexYiningLiu** [ManWingloeng/nailtracking#5]
Is there any method that makes it possible to distinguish between nails? I.e. I want to know if a bounding box's coordinates corresponds specifically to the index finger nail. Thanks.

**Comment by toddwyl** [comment]
We can get the bounding box's coordinates, but cannot distinguish between nails. You can make some rules to distinguish:
1. Find the moments of the hand and calculate the distances between nails and moments.
2. According to the distances, you can distinguish between nails.

Another way may waste some time, you can annotate again the nails of which finger.
