### ISSUE TITLE
Potential usage - reaching out

### ISSUE THREAD

**Issue by Crooper** [ManWingloeng/nailtracking#6]
Hi YongLiang,

Reaching out as I work for a production company and we have a project that would use a similar model than this. Since you seem to have made some good progress already, wondering if you'd be open to chat about your results and potentially help out further. Feel free to reach us through our [official website](https://www.mediamonks.com/), under the Shanghai office (contacts at the bottom of the homepage).

Cheers!

Quentin

**Comment by toddwyl** [comment]
Sorry, I am not interested in this, thank you for your support of my repo. If there is follow-up progress, I will contact you. @Crooper
